---
- name: Install nginx webserver
  hosts: all
  become: yes

  tasks:
  - name: Install Nginx Package
    shell: amazon-linux-extras install nginx1.12 -y
    

  - name: Copy Application Code
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start Hello World Application
    service:
      name: nginx
      state: started
