---
- name: Install nginx webserver
  hosts: all
  become: yes

  tasks:
  - name: Install Nginx Package
    shell: amazon-linux-extras install nginx1.12 -y
    
  - name: 
    file:
      path: /usr/share/nginx/html/
      state: directory
      mode: 0777
      owner: root
      group: root
    
  - name: Download latest Application code from S3
    get_url:
      url: https://s3.amazonaws.com/hello-world-application-code/index.html
      dest: /usr/share/nginx/html/
      mode: 0777
    
  #tasks:
  #- name: Install Nginx Package
    #shell: wget https://s3.amazonaws.com/hello-world-application-code/index.html
    
    
    
    
  #- name: Download latest Application code from S3
    #s3:
      #bucket: hello-world-application-code
      #object: index.html
      #dest: /usr/share/nginx/html/index.html
      #mode: get  

  #- name: Copy Application Code
    #template:
      #src: index.html
      #dest: /usr/share/nginx/html/index.html

  - name: Start Hello World Application
    service:
      name: nginx
      state: started
